name: ai-eng-check
# Generated by ai-eng init — the CI gate.
#
# Two rules this file obeys on purpose:
#   · the governor is the *released binary*, pinned by version + sha256, so the
#     project needs no runtime for it and the version is bumped deliberately;
#   · every action is pinned by commit SHA — a tag is mutable, a SHA is not, and
#     this workflow is the one an agent is told not to touch (§17).
on: [push, pull_request]

# The client's job needs to read its own repository and nothing else: the governor is
# fetched from a release, and the attestation check is a read too.
permissions:
  contents: read

env:
  AI_ENG_VERSION: v2.0.0-rc.1

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      # Bun from npm, not from an action: not every organization permits a given
      # third-party action, and one that does not makes the whole workflow fail at
      # startup with no logs at all. Node is on every hosted runner, and the registry
      # pins the version's integrity itself.
      - run: npm install -g bun@1.4.2

      # The checksum alone proves nothing: binary and manifest come from the same
      # place, so whoever can write one can write both. The attestation is what binds
      # these bytes to a commit in the repository that built them, and it is why the
      # release job verifies it before publishing (release.yml).
      - name: Install the governor (released binary, provenance-verified)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          base="https://github.com/arcasilesgroup/ai-engineering/releases/download/${AI_ENG_VERSION}"
          curl -sSfL -o ai-eng "$base/ai-eng-linux-x64"
          curl -sSfL -o CHECKSUMS-SHA256.txt "$base/CHECKSUMS-SHA256.txt"
          awk '$2=="ai-eng-linux-x64"{print $1"  ai-eng"}' CHECKSUMS-SHA256.txt | sha256sum -c -
          gh attestation verify ai-eng \
            --repo arcasilesgroup/ai-engineering \
            --signer-workflow arcasilesgroup/ai-engineering/.github/workflows/release.yml \
            --source-ref "refs/tags/${AI_ENG_VERSION}" \
            --deny-self-hosted-runners
          mkdir -p "$HOME/.local/bin"
          install -m 0755 ai-eng "$HOME/.local/bin/ai-eng"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Install the canon the contract runner reads (machine side, no repo files)
        run: ai-eng init --global --yes

      - name: Dependencies (only when the project is a JavaScript one)
        run: |
          set -euo pipefail
          if [ -f bun.lock ] || [ -f bun.lockb ]; then bun install --frozen-lockfile
          elif [ -f package.json ]; then echo "package.json without a bun lockfile — install with your own package manager step"
          else echo "no package.json — the project brings its own runtime"; fi

      # One step, one rule: run only what the project declares. `bun run --if-present`
      # skips an undeclared script and propagates a declared one's failure — but with
      # no package.json at all it falls through to the shell's own `test` builtin,
      # which exits 1 and reddens a project that declares nothing.
      - name: Project checks — typecheck · lint · test · arch, only when declared
        run: |
          set -euo pipefail
          if [ ! -f package.json ]; then echo "no package.json — this project declares no JavaScript checks"; exit 0; fi
          for check in typecheck lint test arch; do
            echo "→ $check"
            bun run --if-present "$check"
          done

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: gitleaks (pinned by version + sha256)
        run: |
          set -euo pipefail
          ver=8.30.0
          curl -sSfL -o gitleaks.tgz "https://github.com/gitleaks/gitleaks/releases/download/v${ver}/gitleaks_${ver}_linux_x64.tar.gz"
          echo "79a3ab579b53f71efd634f3aaf7e04a0fa0cf206b7ed434638d1547a2470a66e  gitleaks.tgz" | sha256sum -c -
          tar -xzf gitleaks.tgz gitleaks
          ./gitleaks detect --redact -v --no-banner

      # --config p/ci, never `auto`: auto refuses to run with metrics off, and a
      # governance gate that phones home is not a governance gate.
      - name: semgrep (pinned, no telemetry)
        run: |
          pipx install semgrep==1.172.0
          semgrep scan --error --config p/ci --metrics=off

      - name: trivy (version + sha256, no action — some orgs allow only GitHub's own)
        run: |
          set -euo pipefail
          ver=0.74.0
          curl -sSfL -o trivy.tgz "https://github.com/aquasecurity/trivy/releases/download/v${ver}/trivy_${ver}_Linux-64bit.tar.gz"
          echo "2ae6fe3ee734b7fdf11335663e18c75ea12dccc76062f09f164a3b0f8be4371a  trivy.tgz" | sha256sum -c -
          tar -xzf trivy.tgz trivy
          ./trivy fs --scanners vuln,misconfig --severity HIGH,CRITICAL --exit-code 1 --quiet .
